### ISSUE TITLE
Can we finish the challenge as a group of 2

### ISSUE THREAD

**Issue by justKMM** [check24-scholarships/check24-best-combination-challenge#2]
Hi can a friend of my and I do the challenge together? I also want to hone my teamwork skill, working in an agile team.

**Comment by tutNichts** [comment]
Hi!

We appreciate your ambition and the idea of participating as a team. This challenge serves as an application for the scholarship, which is why it is important for us to see and evaluate individual performances.

Unfortunately, group work is not suitable for the GenDev Coding Challenge.
We look forward to your individual submissions!

Good luck! 🚀
